/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pages;


import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import services.*;

/**
 *
 * @author Дом
 */
public class CreateJobPage extends javax.swing.JFrame {
    public File bashScript;
    public File InputFile;
    public File JobFile;
    public static SubmitJobPage submitJobPage;
     
    
    

    /**
     * Creates new form CreateJobPage
     */
    public CreateJobPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        TopLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        OpenJobBtn = new javax.swing.JButton();
        CreateJobBtn = new javax.swing.JButton();
        ClearFieldsBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        BashScriptPanel = new javax.swing.JPanel();
        CreateBashScriptBtn = new javax.swing.JButton();
        SelectProgCB = new javax.swing.JComboBox();
        SelectProgLb = new javax.swing.JLabel();
        SelectInputLb = new javax.swing.JLabel();
        SelectInFile = new javax.swing.JButton();
        inputFileLb = new javax.swing.JLabel();
        SelectResolLb = new javax.swing.JLabel();
        SelectResolCB = new javax.swing.JComboBox();
        errorLabel = new javax.swing.JLabel();
        GeneralPanel = new javax.swing.JPanel();
        ExecutLb = new javax.swing.JLabel();
        JobNameLb = new javax.swing.JLabel();
        JobName = new javax.swing.JTextField();
        InputFileLb = new javax.swing.JLabel();
        SelectInputFileBtn = new javax.swing.JButton();
        SelectFileLb = new javax.swing.JLabel();
        SelectInputFileLb = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        stdoutLb = new javax.swing.JLabel();
        stdout = new javax.swing.JTextField();
        stderrLb = new javax.swing.JLabel();
        stderr = new javax.swing.JTextField();
        SelectSHCB = new javax.swing.JComboBox();
        SelectInputFileLb2 = new javax.swing.JLabel();
        SelectInputFileBtn2 = new javax.swing.JButton();
        SelectInputFileBtn3 = new javax.swing.JButton();
        SelectInputFileLb3 = new javax.swing.JLabel();
        SelectInputFileBtn4 = new javax.swing.JButton();
        SelectInputFileLb4 = new javax.swing.JLabel();
        EnvironmentPanel = new javax.swing.JPanel();
        gmlogLb = new javax.swing.JLabel();
        gmlog = new javax.swing.JTextField();
        wallTimeLb = new javax.swing.JLabel();
        wallTime = new javax.swing.JTextField();
        countLb = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        queueLb = new javax.swing.JLabel();
        queue = new javax.swing.JTextField();
        SaveEnvBtn = new javax.swing.JButton();
        runtimeenvironmentLb = new javax.swing.JLabel();
        runtimeenvironment = new javax.swing.JTextField();
        ResultScrollPane = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopPanel.setBackground(new java.awt.Color(153, 255, 255));
        TopPanel.setForeground(new java.awt.Color(0, 0, 153));
        TopPanel.setToolTipText("Grid Node");
        TopPanel.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N

        TopLabel.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        TopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TopLabel.setText("Grid Node");
        TopLabel.setToolTipText("");

        MainPanel.setBackground(new java.awt.Color(204, 255, 255));

        OpenJobBtn.setBackground(new java.awt.Color(0, 204, 204));
        OpenJobBtn.setText("Open Job");
        OpenJobBtn.setActionCommand("Registration");
        OpenJobBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpenJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenJobBtnActionPerformed(evt);
            }
        });

        CreateJobBtn.setBackground(new java.awt.Color(0, 204, 204));
        CreateJobBtn.setText("Create .xrsl File");
        CreateJobBtn.setActionCommand("Registration");
        CreateJobBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJobBtnActionPerformed(evt);
            }
        });

        ClearFieldsBtn.setBackground(new java.awt.Color(0, 204, 204));
        ClearFieldsBtn.setText("Clear Fields");
        ClearFieldsBtn.setActionCommand("Registration");
        ClearFieldsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearFieldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(0, 204, 204));
        CancelBtn.setText("Cancel");
        CancelBtn.setActionCommand("Registration");
        CancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        MainTabbedPane.setBackground(new java.awt.Color(204, 255, 255));
        MainTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        BashScriptPanel.setBackground(new java.awt.Color(153, 255, 255));

        CreateBashScriptBtn.setBackground(new java.awt.Color(0, 204, 204));
        CreateBashScriptBtn.setText("Create Bash Script");
        CreateBashScriptBtn.setActionCommand("Registration");
        CreateBashScriptBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateBashScriptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBashScriptBtnActionPerformed(evt);
            }
        });

        SelectProgCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "....................", "Quantum Espresso" }));
        SelectProgCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProgCBActionPerformed(evt);
            }
        });

        SelectProgLb.setText("Select Program");
        SelectProgLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SelectInputLb.setText("Select Input File");
        SelectInputLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SelectInFile.setText("Select");
        SelectInFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInFileActionPerformed(evt);
            }
        });

        inputFileLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SelectResolLb.setText("Select Resolution");
        SelectResolLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SelectResolCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "....................", "pw.x" }));
        SelectResolCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectResolCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BashScriptPanelLayout = new javax.swing.GroupLayout(BashScriptPanel);
        BashScriptPanel.setLayout(BashScriptPanelLayout);
        BashScriptPanelLayout.setHorizontalGroup(
            BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BashScriptPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                                .addComponent(SelectProgLb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectProgCB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                                .addComponent(SelectResolLb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectResolCB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                                .addComponent(SelectInputLb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectInFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BashScriptPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(BashScriptPanelLayout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(CreateBashScriptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        BashScriptPanelLayout.setVerticalGroup(
            BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectProgCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectProgLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputFileLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SelectInputLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectInFile)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectResolCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectResolLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(CreateBashScriptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(errorLabel)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Bash Script", BashScriptPanel);

        GeneralPanel.setBackground(new java.awt.Color(153, 255, 255));

        ExecutLb.setText("Select executable .sh");

        JobNameLb.setText("Job Name");

        InputFileLb.setText("Input Files");

        SelectInputFileBtn.setText("Select First Input File");
        SelectInputFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInputFileBtnActionPerformed(evt);
            }
        });

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        stdoutLb.setText("stdout");

        stderrLb.setText("stderr");

        SelectSHCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...................." }));
        SelectSHCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectSHCBActionPerformed(evt);
            }
        });

        SelectInputFileBtn2.setText("Select Second Input File");
        SelectInputFileBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInputFileBtn2ActionPerformed(evt);
            }
        });

        SelectInputFileBtn3.setText("Select Third Input File");
        SelectInputFileBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInputFileBtn3ActionPerformed(evt);
            }
        });

        SelectInputFileBtn4.setText("Select Fourth Input File");
        SelectInputFileBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInputFileBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stdoutLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InputFileLb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExecutLb, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralPanelLayout.createSequentialGroup()
                                .addComponent(SelectSHCB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralPanelLayout.createSequentialGroup()
                                .addComponent(SelectInputFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectInputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JobNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                                        .addComponent(SelectInputFileBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(SelectInputFileLb3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(stdout, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(stderrLb, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))
                                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(SelectInputFileBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(SelectInputFileBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JobName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(SelectInputFileLb4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelectInputFileLb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stderr))))
                .addContainerGap())
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SelectSHCB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ExecutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JobName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JobNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(SelectInputFileLb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SelectInputFileLb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SelectInputFileBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SelectInputFileBtn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SelectInputFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SelectInputFileLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(3, 3, 3)
                                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SelectInputFileLb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(SelectInputFileBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stderr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stderrLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(InputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(stdoutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveBtn)
                .addGap(37, 37, 37))
        );

        MainTabbedPane.addTab("General", GeneralPanel);

        EnvironmentPanel.setBackground(new java.awt.Color(153, 255, 255));

        gmlogLb.setText("gmlog");

        wallTimeLb.setText("wallTime");

        countLb.setText("count");

        queueLb.setText("queue");

        SaveEnvBtn.setText("Save");
        SaveEnvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEnvBtnActionPerformed(evt);
            }
        });

        runtimeenvironmentLb.setText("run time environment");

        javax.swing.GroupLayout EnvironmentPanelLayout = new javax.swing.GroupLayout(EnvironmentPanel);
        EnvironmentPanel.setLayout(EnvironmentPanelLayout);
        EnvironmentPanelLayout.setHorizontalGroup(
            EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(runtimeenvironmentLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(runtimeenvironment))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(countLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(count))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(gmlogLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gmlog, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(queueLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wallTimeLb, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wallTime, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(queue))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnvironmentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveEnvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        EnvironmentPanelLayout.setVerticalGroup(
            EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gmlogLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gmlog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wallTimeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(countLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(queueLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(wallTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(queue, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runtimeenvironmentLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runtimeenvironment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(SaveEnvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Environment", EnvironmentPanel);

        MainTabbedPane.setSelectedComponent(BashScriptPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainTabbedPane.getAccessibleContext().setAccessibleName("");

        ResultScrollPane.setViewportView(Result);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResultScrollPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                        .addComponent(OpenJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearFieldsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearFieldsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenJobBtnActionPerformed
 JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            JobFile = fileChooser.getSelectedFile();
            Result.setText(JobFile.getName());

        } else {
            System.out.println("File access cancelled by user.");

        }
    }//GEN-LAST:event_OpenJobBtnActionPerformed

    private void CreateJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJobBtnActionPerformed
        Socket socket = null;
       
        try {
            socket = new Socket("localhost", 9999);
        } catch (IOException ex) {
            Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        fileName = JOptionPane.showInputDialog("Enter file name");
        String resultXRSL = Result.getText();
	 if (fileName != null && resultXRSL!= null) {
                

                
                ArrayList<String> my = new ArrayList<String>();
                my.add(0, fileName);
                my.add(1, resultXRSL);
                String command = "createXRSLFile";
                PrintWriter toClient = null;
            try {
                toClient = new PrintWriter(socket.getOutputStream(), true);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                    toClient.println(command);
                ObjectOutputStream objectOutput = null;
            try {
                objectOutput = new ObjectOutputStream(socket.getOutputStream());
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            try {
                BufferedReader fromServer = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                    
            try {
                objectOutput.writeObject(my);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                    titleList = new ArrayList<String>();
            
                    ObjectInputStream objectInput = null;
            try {
                objectInput = new ObjectInputStream(socket.getInputStream());
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }

                
                    Object object = null;
            try {
                object = objectInput.readObject();
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
                    titleList = (ArrayList<String>) object;
                    System.out.println(titleList);
                    String result = titleList.get(0);
                    System.out.println(result);
                    errorLabel.setText(result);
                    SubmitJobPage.SelectJobFileCB.addItem(fileName);
                    
             
               
                    
                    
                    
                   
           

        }
        submitJobPage = new SubmitJobPage();
        submitJobPage.setVisible(true);
        ProfilePage.createJobPage.setVisible(false);
    }//GEN-LAST:event_CreateJobBtnActionPerformed

    private void ClearFieldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsBtnActionPerformed
        Result.setText("");
        SelectFileLb.setText("");
        JobName.setText("");
        SelectInputFileLb.setText("");
        stdout.setText("");
        stderr.setText("");
        gmlog.setText("");
        wallTime.setText("");
        count.setText("");
        queue.setText("");
        runtimeenvironment.setText("");
    }//GEN-LAST:event_ClearFieldsBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        
        LoginPage.profilePage.setVisible(true);
        ProfilePage.createJobPage.setVisible(false);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void CreateBashScriptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBashScriptBtnActionPerformed
         Socket socket = null;
        try {
            socket = new Socket("localhost", 9999);
        } catch (IOException ex) {
            Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        fileName = JOptionPane.showInputDialog("Enter file name");
        String resultSH = Result.getText();
	 if (fileName != null && resultSH!= null) {
                SelectSHCB.addItem(fileName);

            try {
                
                ArrayList<String> my = new ArrayList<String>();
                my.add(0, fileName);
                my.add(1, resultSH);
                String command = "createSHFile";
                PrintWriter toClient = new PrintWriter(socket.getOutputStream(), true);
                    toClient.println(command);
                ObjectOutputStream objectOutput = new ObjectOutputStream(socket.getOutputStream());
                
                BufferedReader fromServer = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                try {
                    
                    objectOutput.writeObject(my);
                    titleList = new ArrayList<String>();
            
                    ObjectInputStream objectInput = new ObjectInputStream(socket.getInputStream());

                
                    Object object = objectInput.readObject();
                    titleList = (ArrayList<String>) object;
                    System.out.println(titleList);
                    String result = titleList.get(0);
                    System.out.println(result);
                    errorLabel.setText(result);
                    
                    

                } catch (IOException e) {
                    e.printStackTrace();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
                }
               
                    
                    
                    
                   
                
            } catch (UnknownHostException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }


        }
    }//GEN-LAST:event_CreateBashScriptBtnActionPerformed

    private void SelectProgCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProgCBActionPerformed
       if(SelectProgCB.getSelectedItem().toString()=="LAMMPS"){

           Result.setText("#!/bin/bash" + "\n"+
                   "\r\n"+"$LMP_MPIRUN <in");
      }
       if(SelectProgCB.getSelectedItem().toString()=="Quantum Espresso"){
           queue.setText("mult.q");
           gmlog.setText("gridlog");
           runtimeenvironment.setText("Espresso-OPENMPI-12");
           stderr.setText("espresso.err");
           stdout.setText("espresso.out");

           Result.setText("#!/bin/bash" + "\n"+
                   "\r\n"+"$QE_MPIRUN $QE_PATH/");
      }
        if(SelectProgCB.getSelectedItem().toString()=="GROMACS"){
           Result.setText("#!/bin/bash\n" +
                   "$GMX_MDRUN -v -deffnm em");
      }
        if(SelectProgCB.getSelectedItem().toString()=="DL_POLY Classic"){
           Result.setText("#!/bin/bash\n" +
                   "$DLC_MPIRUN");
      }
        if(SelectProgCB.getSelectedItem().toString()=="MPI"){
           Result.setText("#!/bin/bash\n" +
                   "chmod +x myprog\n" +
                   "$MPIRUN myprog");
      }
        if(SelectProgCB.getSelectedItem().toString()=="...................."){

           Result.setText("");
      }
    }//GEN-LAST:event_SelectProgCBActionPerformed

    private void SelectInFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
         int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            inputFileLb.setText(InputFile.getName());
            SelectInputFileLb.setText(inputFileLb.getText()); 
            try {
                SelectFile.SelectFile(InputFile, errorLabel);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SelectInFileActionPerformed

    private void SelectResolCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectResolCBActionPerformed
        if(SelectResolCB.getSelectedItem().toString()=="pw.x"){
            
            String inputFile= InputFile.getName();
            String outputFile = inputFile.replaceAll(".in", ".out");

           Result.setText("#!/bin/bash" + "\n"+
                   "\r\n"+"$QE_MPIRUN $QE_PATH/pw.x <"+inputFile+"> "+outputFile);
      }
        if(SelectResolCB.getSelectedItem().toString()=="...................."){

           Result.setText("");
      }
    }//GEN-LAST:event_SelectResolCBActionPerformed

    private void SaveEnvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEnvBtnActionPerformed

        if (!SelectInputFileLb4.getText().isEmpty()
                &&!SelectInputFileLb3.getText().isEmpty()
                &&!SelectInputFileLb2.getText().isEmpty()
                &&!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb3.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb4.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")"
                + "\n(gmlog="+gmlog.getText()+")"
                + "\n(wallTime="+wallTime.getText()+")"
                + "\n(count="+count.getText()+")"
                + "\n(queue="+queue.getText()+")"
                + "\n(runtimeenvironment="+runtimeenvironment.getText()+")");
        }else if(!SelectInputFileLb3.getText().isEmpty()
                &&!SelectInputFileLb2.getText().isEmpty()
                &&!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb3.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")"
                + "\n(gmlog="+gmlog.getText()+")"
                + "\n(wallTime="+wallTime.getText()+")"
                + "\n(count="+count.getText()+")"
                + "\n(queue="+queue.getText()+")"
                + "\n(runtimeenvironment="+runtimeenvironment.getText()+")");
            
        }else if(!SelectInputFileLb2.getText().isEmpty()
                && !SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")"
                + "\n(gmlog="+gmlog.getText()+")"
                + "\n(wallTime="+wallTime.getText()+")"
                + "\n(count="+count.getText()+")"
                + "\n(queue="+queue.getText()+")"
                + "\n(runtimeenvironment="+runtimeenvironment.getText()+")");
            
        }else if(!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")"
                + "\n(gmlog="+gmlog.getText()+")"
                + "\n(wallTime="+wallTime.getText()+")"
                + "\n(count="+count.getText()+")"
                + "\n(queue="+queue.getText()+")"
                + "\n(runtimeenvironment="+runtimeenvironment.getText()+")");
            
        }

    }//GEN-LAST:event_SaveEnvBtnActionPerformed

    private void SelectSHCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectSHCBActionPerformed

        if(SelectProgCB.getSelectedItem().toString()=="...................."){

            SelectFileLb.setText("");
        }  else{
            String SHFileName= SelectSHCB.getSelectedItem().toString();
            SelectFileLb.setText(SHFileName+".sh");
        }
    }//GEN-LAST:event_SelectSHCBActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if (!SelectInputFileLb4.getText().isEmpty()
                &&!SelectInputFileLb3.getText().isEmpty()
                &&!SelectInputFileLb2.getText().isEmpty()
                &&!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb3.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb4.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")");
        }else if(!SelectInputFileLb3.getText().isEmpty()
                &&!SelectInputFileLb2.getText().isEmpty()
                &&!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb3.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")");
            
        }else if(!SelectInputFileLb2.getText().isEmpty()
                && !SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "(\""+SelectInputFileLb2.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")");
            
        }else if(!SelectInputFileLb.getText().isEmpty()){
            Result.setText("&(exectutable="+SelectFileLb.getText() +
                ")\n(jobname="+JobName.getText()+
                ")\n(inputFiles=(\""+SelectInputFileLb.getText()+"\" \" \" )) "
                + "\n(outputFiles=(\"/\" \" \"))"
                + "\n(stdout="+stdout.getText()+")"
                + "\n(stderr="+stderr.getText()+")");
            
        }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void SelectInputFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInputFileBtnActionPerformed

        JFileChooser fileChooser = new JFileChooser();
         int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            SelectInputFileLb.setText(InputFile.getName());
           
            try {
                SelectFile.SelectFile(InputFile, errorLabel);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    
        
    }//GEN-LAST:event_SelectInputFileBtnActionPerformed

    private void SelectInputFileBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInputFileBtn2ActionPerformed
      JFileChooser fileChooser = new JFileChooser();
         int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            SelectInputFileLb2.setText(InputFile.getName());
           
            try {
                SelectFile.SelectFile(InputFile, errorLabel);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_SelectInputFileBtn2ActionPerformed

    private void SelectInputFileBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInputFileBtn3ActionPerformed
       JFileChooser fileChooser = new JFileChooser();
         int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            SelectInputFileLb3.setText(InputFile.getName());
           
            try {
                SelectFile.SelectFile(InputFile, errorLabel);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SelectInputFileBtn3ActionPerformed

    private void SelectInputFileBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInputFileBtn4ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
         int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            SelectInputFileLb4.setText(InputFile.getName());
           
            try {
                SelectFile.SelectFile(InputFile, errorLabel);
            } catch (IOException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateJobPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SelectInputFileBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateJobPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BashScriptPanel;
    public javax.swing.JButton CancelBtn;
    public javax.swing.JButton ClearFieldsBtn;
    public javax.swing.JButton CreateBashScriptBtn;
    public javax.swing.JButton CreateJobBtn;
    public javax.swing.JPanel EnvironmentPanel;
    public javax.swing.JLabel ExecutLb;
    public javax.swing.JPanel GeneralPanel;
    public javax.swing.JLabel InputFileLb;
    public javax.swing.JTextField JobName;
    public javax.swing.JLabel JobNameLb;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane MainTabbedPane;
    public javax.swing.JButton OpenJobBtn;
    public javax.swing.JTextPane Result;
    public javax.swing.JScrollPane ResultScrollPane;
    public javax.swing.JButton SaveBtn;
    public javax.swing.JButton SaveEnvBtn;
    public javax.swing.JLabel SelectFileLb;
    private javax.swing.JButton SelectInFile;
    private javax.swing.JButton SelectInputFileBtn;
    public javax.swing.JButton SelectInputFileBtn2;
    private javax.swing.JButton SelectInputFileBtn3;
    public javax.swing.JButton SelectInputFileBtn4;
    public javax.swing.JLabel SelectInputFileLb;
    public javax.swing.JLabel SelectInputFileLb2;
    public javax.swing.JLabel SelectInputFileLb3;
    public javax.swing.JLabel SelectInputFileLb4;
    public javax.swing.JLabel SelectInputLb;
    public javax.swing.JComboBox SelectProgCB;
    public javax.swing.JLabel SelectProgLb;
    public javax.swing.JComboBox SelectResolCB;
    public javax.swing.JLabel SelectResolLb;
    public javax.swing.JComboBox SelectSHCB;
    private javax.swing.JLabel TopLabel;
    public javax.swing.JPanel TopPanel;
    public javax.swing.JTextField count;
    public javax.swing.JLabel countLb;
    private javax.swing.JLabel errorLabel;
    public javax.swing.JTextField gmlog;
    public javax.swing.JLabel gmlogLb;
    public javax.swing.JLabel inputFileLb;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField queue;
    public javax.swing.JLabel queueLb;
    public javax.swing.JTextField runtimeenvironment;
    public javax.swing.JLabel runtimeenvironmentLb;
    public javax.swing.JTextField stderr;
    public javax.swing.JLabel stderrLb;
    public javax.swing.JTextField stdout;
    public javax.swing.JLabel stdoutLb;
    public javax.swing.JTextField wallTime;
    public javax.swing.JLabel wallTimeLb;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<String> titleList;
    public static String fileName;
    public JButton SelectSecondInputFileBtn;
    public static javax.swing.GroupLayout GeneralPanelLayout;
    
    
}
