/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Pages;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author Дом
 */
public class CreateJobPage extends javax.swing.JFrame {
    public File bashScript;
    public File InputFile;
    public File JobFile;
    public static SubmitJobPage submitJobPage;
    

    /**
     * Creates new form CreateJobPage
     */
    public CreateJobPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        TopLabel = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        OpenJobBtn = new javax.swing.JButton();
        CreateJobBtn = new javax.swing.JButton();
        ClearFieldsBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        BashScriptPanel = new javax.swing.JPanel();
        CreateBashScriptBtn = new javax.swing.JButton();
        SelectProgCB = new javax.swing.JComboBox();
        SelectProgLb = new javax.swing.JLabel();
        GeneralPanel = new javax.swing.JPanel();
        ExecutLb = new javax.swing.JLabel();
        SelectFileBtn = new javax.swing.JButton();
        JobNameLb = new javax.swing.JLabel();
        JobName = new javax.swing.JTextField();
        InputFileLb = new javax.swing.JLabel();
        SelectInputFileBtn = new javax.swing.JButton();
        OutputFileLb = new javax.swing.JLabel();
        OutputFile = new javax.swing.JTextField();
        SelectFileLb = new javax.swing.JLabel();
        SelectInputFileLb = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        stdoutLb = new javax.swing.JLabel();
        stdout = new javax.swing.JTextField();
        stderrLb = new javax.swing.JLabel();
        stderr = new javax.swing.JTextField();
        EnvironmentPanel = new javax.swing.JPanel();
        gmlogLb = new javax.swing.JLabel();
        gmlog = new javax.swing.JTextField();
        wallTimeLb = new javax.swing.JLabel();
        wallTime = new javax.swing.JTextField();
        memoryLb = new javax.swing.JLabel();
        memory = new javax.swing.JTextField();
        countLb = new javax.swing.JLabel();
        count = new javax.swing.JTextField();
        SaveEnvBtn = new javax.swing.JButton();
        runtimeenvironmentLb = new javax.swing.JLabel();
        runtimeenvironment = new javax.swing.JTextField();
        ResultScrollPane = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TopPanel.setBackground(new java.awt.Color(153, 255, 255));
        TopPanel.setForeground(new java.awt.Color(0, 0, 153));
        TopPanel.setToolTipText("Grid Node");
        TopPanel.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N

        TopLabel.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        TopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TopLabel.setText("Grid Node");
        TopLabel.setToolTipText("");

        MainPanel.setBackground(new java.awt.Color(204, 255, 255));

        OpenJobBtn.setBackground(new java.awt.Color(0, 204, 204));
        OpenJobBtn.setText("Open Job");
        OpenJobBtn.setActionCommand("Registration");
        OpenJobBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OpenJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenJobBtnActionPerformed(evt);
            }
        });

        CreateJobBtn.setBackground(new java.awt.Color(0, 204, 204));
        CreateJobBtn.setText("Create Job");
        CreateJobBtn.setActionCommand("Registration");
        CreateJobBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJobBtnActionPerformed(evt);
            }
        });

        ClearFieldsBtn.setBackground(new java.awt.Color(0, 204, 204));
        ClearFieldsBtn.setText("Clear Fields");
        ClearFieldsBtn.setActionCommand("Registration");
        ClearFieldsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ClearFieldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(0, 204, 204));
        CancelBtn.setText("Cancel");
        CancelBtn.setActionCommand("Registration");
        CancelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        MainTabbedPane.setBackground(new java.awt.Color(204, 255, 255));

        BashScriptPanel.setBackground(new java.awt.Color(153, 255, 255));

        CreateBashScriptBtn.setBackground(new java.awt.Color(0, 204, 204));
        CreateBashScriptBtn.setText("Create Bash Script");
        CreateBashScriptBtn.setActionCommand("Registration");
        CreateBashScriptBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CreateBashScriptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBashScriptBtnActionPerformed(evt);
            }
        });

        SelectProgCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "....................", "LAMMPS", "GROMACS", "DL_POLY Classic", "MPI" }));
        SelectProgCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProgCBActionPerformed(evt);
            }
        });

        SelectProgLb.setText("Select Program");
        SelectProgLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout BashScriptPanelLayout = new javax.swing.GroupLayout(BashScriptPanel);
        BashScriptPanel.setLayout(BashScriptPanelLayout);
        BashScriptPanelLayout.setHorizontalGroup(
            BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BashScriptPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(SelectProgLb, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(SelectProgCB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BashScriptPanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(CreateBashScriptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        BashScriptPanelLayout.setVerticalGroup(
            BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BashScriptPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BashScriptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectProgLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectProgCB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(CreateBashScriptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        MainTabbedPane.addTab("Bash Script", BashScriptPanel);

        GeneralPanel.setBackground(new java.awt.Color(153, 255, 255));

        ExecutLb.setText("Executable");

        SelectFileBtn.setText("Select Bash Script");
        SelectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFileBtnActionPerformed(evt);
            }
        });

        JobNameLb.setText("Job Name");

        InputFileLb.setText("Input File");

        SelectInputFileBtn.setText("Select Input File");
        SelectInputFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectInputFileBtnActionPerformed(evt);
            }
        });

        OutputFileLb.setText("Output File");

        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        stdoutLb.setText("stdout");

        stderrLb.setText("stderr");

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(ExecutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(JobNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JobName))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(InputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SelectInputFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(OutputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(OutputFile)))
                        .addGap(35, 35, 35)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectInputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(stdoutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stdout))
                            .addGroup(GeneralPanelLayout.createSequentialGroup()
                                .addComponent(stderrLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stderr)))
                        .addGap(127, 127, 127)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExecutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SelectFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SelectFileLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectInputFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectInputFileLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputFileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GeneralPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SaveBtn)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdoutLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stderrLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stderr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        MainTabbedPane.addTab("General", GeneralPanel);

        EnvironmentPanel.setBackground(new java.awt.Color(153, 255, 255));

        gmlogLb.setText("gmlog");

        wallTimeLb.setText("wallTime");

        memoryLb.setText("memory");

        countLb.setText("count");

        SaveEnvBtn.setText("Save");
        SaveEnvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEnvBtnActionPerformed(evt);
            }
        });

        runtimeenvironmentLb.setText("run time environment");

        javax.swing.GroupLayout EnvironmentPanelLayout = new javax.swing.GroupLayout(EnvironmentPanel);
        EnvironmentPanel.setLayout(EnvironmentPanelLayout);
        EnvironmentPanelLayout.setHorizontalGroup(
            EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(runtimeenvironmentLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(runtimeenvironment))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(countLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(count))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(memoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(memory))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(wallTimeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(wallTime))
                    .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                        .addComponent(gmlogLb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gmlog, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                .addGap(132, 132, 132)
                .addComponent(SaveEnvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        EnvironmentPanelLayout.setVerticalGroup(
            EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnvironmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gmlogLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmlog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wallTimeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wallTime, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memoryLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveEnvBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EnvironmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runtimeenvironmentLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runtimeenvironment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("Environment", EnvironmentPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainTabbedPane.getAccessibleContext().setAccessibleName("");

        ResultScrollPane.setViewportView(Result);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResultScrollPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                        .addComponent(OpenJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearFieldsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreateJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearFieldsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenJobBtnActionPerformed
 JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            JobFile = fileChooser.getSelectedFile();
            Result.setText(JobFile.getName());

        } else {
            System.out.println("File access cancelled by user.");

        }
    }//GEN-LAST:event_OpenJobBtnActionPerformed

    private void CreateJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJobBtnActionPerformed
        String fileName = JOptionPane.showInputDialog("Enter file name");
	FileWriter outFile = null;
        try {
//            outFile = new FileWriter(fileName +".txt",true);
          outFile = new FileWriter(fileName +".xrsl",true);
	} catch (IOException e1) {
		e1.printStackTrace();
		}
	try {
            outFile.write(Result.getText());
		} catch (IOException e1) {
		e1.printStackTrace();
				}
	try {
	outFile.close();
        
        } catch (IOException e1) {
	e1.printStackTrace();
        }
        submitJobPage = new SubmitJobPage();
        submitJobPage.setVisible(true);
        ProfilePage.createJobPage.setVisible(false);
    }//GEN-LAST:event_CreateJobBtnActionPerformed

    private void ClearFieldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsBtnActionPerformed
        Result.setText("");
        SelectFileLb.setText("");
        JobName.setText("");
        SelectInputFileLb.setText("");
        OutputFile.setText("");
        stdout.setText("");
        stderr.setText("");
        gmlog.setText("");
        wallTime.setText("");
        memory.setText("");
        count.setText("");
        runtimeenvironment.setText("");
    }//GEN-LAST:event_ClearFieldsBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        
        LoginPage.profilePage.setVisible(true);
        ProfilePage.createJobPage.setVisible(false);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void CreateBashScriptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBashScriptBtnActionPerformed
        String fileName = JOptionPane.showInputDialog("Enter file name");
	FileWriter outFile = null;
        try {
//            outFile = new FileWriter(fileName +".txt",true);
          outFile = new FileWriter(fileName +".sh",true);
	} catch (IOException e1) {
		e1.printStackTrace();
		}
	try {
            outFile.write(Result.getText());
		} catch (IOException e1) {
		e1.printStackTrace();
				}
	try {
	outFile.close();
        } catch (IOException e1) {
	e1.printStackTrace();
        }
    }//GEN-LAST:event_CreateBashScriptBtnActionPerformed

    private void SelectProgCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProgCBActionPerformed
       if(SelectProgCB.getSelectedItem().toString()=="LAMMPS"){

           Result.setText("#!/bin/bash" + "\n"+
                   "\r\n"+"$LMP_MPIRUN <in");
      }
        if(SelectProgCB.getSelectedItem().toString()=="GROMACS"){
           Result.setText("#!/bin/bash\n" +
                   "$GMX_MDRUN -v -deffnm em");
      }
        if(SelectProgCB.getSelectedItem().toString()=="DL_POLY Classic"){
           Result.setText("#!/bin/bash\n" +
                   "$DLC_MPIRUN");
      }
        if(SelectProgCB.getSelectedItem().toString()=="MPI"){
           Result.setText("#!/bin/bash\n" +
                   "chmod +x myprog\n" +
                   "$MPIRUN myprog");
      }
    }//GEN-LAST:event_SelectProgCBActionPerformed

    private void SelectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFileBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            bashScript = fileChooser.getSelectedFile();
            SelectFileLb.setText(bashScript.getName());

        } else {
            System.out.println("File access cancelled by user.");

        }
    }//GEN-LAST:event_SelectFileBtnActionPerformed

    private void SelectInputFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectInputFileBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            InputFile = fileChooser.getSelectedFile();
            SelectInputFileLb.setText(InputFile.getName()); 
        } else {
            System.out.println("File access cancelled by user.");

        }

    }//GEN-LAST:event_SelectInputFileBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

        Result.setText("&(exectutable="+SelectFileLb.getText() +")\n(jobname="+JobName.getText()+
	")\n(inputFiles=("+SelectInputFileLb.getText()+" \" \" ))\n(outputFiles=(\""+OutputFile.getText()+
	" \" \"))\n(stdout="+stdout.getText()+".out)\n(stderr="+stderr.getText()+".err)");

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void SaveEnvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEnvBtnActionPerformed

           Result.setText("&(exectutable="+SelectFileLb.getText() +")\n(jobname="+JobName.getText()+
	")\n(inputFiles=("+SelectInputFileLb.getText()+" \" \" ))\n(outputFiles=(\""+OutputFile.getText()+
	" \" \"))\n(stdout="+stdout.getText()+".out)\n(stderr="+stderr.getText()+".err)\n(gmlog="+gmlog.getText()+")\n(wallTime="+wallTime.getText()+")\n"
        + "(memory="+memory.getText()+")\n(count="+count.getText()+")\n(runtimeenvironment=\""+runtimeenvironment.getText()+"\")");
  
    }//GEN-LAST:event_SaveEnvBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateJobPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateJobPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BashScriptPanel;
    public javax.swing.JButton CancelBtn;
    public javax.swing.JButton ClearFieldsBtn;
    public javax.swing.JButton CreateBashScriptBtn;
    public javax.swing.JButton CreateJobBtn;
    public javax.swing.JPanel EnvironmentPanel;
    public javax.swing.JLabel ExecutLb;
    public javax.swing.JPanel GeneralPanel;
    public javax.swing.JLabel InputFileLb;
    public javax.swing.JTextField JobName;
    public javax.swing.JLabel JobNameLb;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTabbedPane MainTabbedPane;
    public javax.swing.JButton OpenJobBtn;
    public javax.swing.JTextField OutputFile;
    public javax.swing.JLabel OutputFileLb;
    public javax.swing.JTextPane Result;
    public javax.swing.JScrollPane ResultScrollPane;
    public javax.swing.JButton SaveBtn;
    public javax.swing.JButton SaveEnvBtn;
    private javax.swing.JButton SelectFileBtn;
    public javax.swing.JLabel SelectFileLb;
    private javax.swing.JButton SelectInputFileBtn;
    public javax.swing.JLabel SelectInputFileLb;
    public javax.swing.JComboBox SelectProgCB;
    public javax.swing.JLabel SelectProgLb;
    private javax.swing.JLabel TopLabel;
    public javax.swing.JPanel TopPanel;
    public javax.swing.JTextField count;
    public javax.swing.JLabel countLb;
    public javax.swing.JTextField gmlog;
    public javax.swing.JLabel gmlogLb;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField memory;
    public javax.swing.JLabel memoryLb;
    public javax.swing.JTextField runtimeenvironment;
    public javax.swing.JLabel runtimeenvironmentLb;
    public javax.swing.JTextField stderr;
    public javax.swing.JLabel stderrLb;
    public javax.swing.JTextField stdout;
    public javax.swing.JLabel stdoutLb;
    public javax.swing.JTextField wallTime;
    public javax.swing.JLabel wallTimeLb;
    // End of variables declaration//GEN-END:variables
}
